### ISSUE TITLE
Make new release with added tests

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/design#1]
- [x] add tests
- [x] set up Travis CI
- [x] set up Codecov 
- [x] set up new webpage
- [x]  publish new release
- [x] redirect package update system to the new webpage

**Comment by fingolfin** [comment]
PR #4 makes progress towards this.

**Comment by fingolfin** [comment]
I believe @lhsoicher took care of all that except for the last point, for which I just made https://github.com/gap-system/gap-distribution/pull/79

@lhsoicher sorry, I told you that I believed that @alex-konovalov surely had picked up the package -- but for that, we need to either update the PackageInfo.g on your homepage with a new one, or alternatively, make a pull request as the one I am linking here. Anyway, once this is done, I am pretty sure the tests for the new design release will go through smoothly.

**Comment by olexandr-konovalov** [comment]
Thanks for sorting this out, @fingolfin! I have merged that PR, so I expect that new release will be picked up tomorrow. @lhsoicher please change the link on your homepage from  http://designtheory.org/software/gap_design/ to https://gap-packages.github.io/design/ (even better, setup a redirect from http://designtheory.org/software/gap_design/  to https://gap-packages.github.io/design/ as well).

**Comment by lhsoicher** [comment]
> @lhsoicher please change the link on your homepage from http://designtheory.org/software/gap_design/ to https://gap-packages.github.io/design/

Done. Link also changed on designtheory.org webpages.

**Comment by olexandr-konovalov** [comment]
Thanks! The new version has been picked up, all tests run smoothly, and it's now included in archives from https://www.gap-system.org/pub/gap/gap4pkgs/ used for testing.
